document.getElementById('generate-button').addEventListener('click', function () {
    const selectedDays = Array.from(document.querySelectorAll('#days-selection input[type="checkbox"]:checked'))
        .map(checkbox => checkbox.nextElementSibling.innerText);
    
    const selectedPuzzles = Array.from(document.querySelectorAll('#puzzle-selection input[type="checkbox"]:checked'))
        .map(checkbox => checkbox.id);
    
    const playerRating = document.getElementById('player-rating').value;
    const hours = parseFloat(document.getElementById('training-hours').value);
    const trainingPlan = document.getElementById('training-plan');
    trainingPlan.innerHTML = ''; // Limpa o plano anterior

    if (selectedDays.length > 0 && playerRating && hours) {
        selectedDays.forEach(day => {
            const table = document.createElement('table');
            table.classList.add('training-table');
            const header = document.createElement('tr');
            header.innerHTML = `<th>Atividade</th><th>Tempo</th>`;
            table.appendChild(header);
            
            let timeAvailable = hours * 60; // Tempo total disponível em minutos

            // Atividades baseadas nos pontos fracos
            const activities = {
                'iniciantes': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '20 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '20 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '20 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '20 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '20 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '25 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '20 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '20 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                },
                '1000': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '20 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '20 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '20 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '20 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '20 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '25 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '20 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '20 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                },
                '1200': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '20 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '20 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '20 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '20 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '20 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '25 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '20 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '20 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                },
                '1400': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '20 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '20 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '20 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '20 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '20 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '25 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '20 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '20 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                    
                },
                '1600': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '20 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '20 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '20 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '20 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '20 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '25 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '20 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '20 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                    
                },
                '1800': {
                    'checkmate': [
                        ['Resolver 10 problemas de xeque-mate em uma jogada', '15 min'],
                        ['Praticar xeque-mate básico (rei e dama contra rei) com um parceiro', '20 min'],
                        ['Resolver 5 problemas de xeque-mate em duas jogadas', '10 min'],
                        ['Jogar uma partida focando em aplicar xeque-mate', '25 min'],
                        ['Praticar finais com rei e torre contra rei', '10 min'],
                        ['Resolver 5 problemas de xeque-mate em três jogadas', '15 min'],
                        ['Analisar uma partida onde um jogador perdeu por xeque-mate', '10 min'],
                        ['Praticar finalizações com rei e bispo contra rei', '20 min'],
                        ['Simulações de xeque-mate com peças menores', '15 min'],
                        ['Resolver problemas de xeque-mate envolvendo defesa', '20 min'],
                        ['Criar 5 situações de xeque-mate em um tabuleiro', '20 min'],
                        ['Discutir táticas de xeque-mate com um parceiro', '15 min'],
                        ['Praticar combinações que levam a xeque-mate', '20 min'],
                        ['Simulações de finais simples buscando xeque-mate', '25 min'],
                        ['Jogar uma partida com foco em evitar xeque-mate', '5 min'],
                    ],
                    'discovered-attack': [
                        ['Resolver 5 exercícios de ataque descoberto em posições práticas', '15 min'],
                        ['Praticar 3 jogadas de ataque descoberto em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de ataque descoberto em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas de ataque descoberto envolvendo peças maiores', '10 min'],
                        ['Simulações de situações de ataque descoberto em partidas', '20 min'],
                        ['Discutir a aplicação de ataques descobertos em finais com um parceiro', '20 min'],
                        ['Resolver exercícios de ataque descoberto em várias posições', '20 min'],
                        ['Praticar ataques descobertos em uma partida online', '25 min'],
                        ['Analisar posições onde o ataque descoberto foi decisivo', '10 min'],
                        ['Jogar uma partida focando em criar situações de ataque descoberto', '25 min'],
                        ['Simulações de táticas de ataque descoberto em blitz', '20 min'],
                        ['Resolver 10 problemas de ataque descoberto', '15 min'],
                        ['Criar 5 posições para explorar ataques descobertos', '20 min'],
                        ['Praticar ataques descobertos em finais simples', '25 min'],
                        ['Simulações de ataques descobertos em diversas partidas', '20 min'],
                    ],
                    'king-side': [
                        ['Resolver 5 problemas de ataque na ala do rei', '15 min'],
                        ['Praticar 5 jogadas de ataque na ala do rei em um jogo amistoso', '10 min'],
                        ['Estudo de padrões de ataque na ala do rei', '20 min'],
                        ['Resolver exercícios práticos sobre ataques na ala do rei', '20 min'],
                        ['Criar 5 situações de ataque na ala do rei em um tabuleiro', '15 min'],
                        ['Simulações de ataques na ala do rei em partidas online', '20 min'],
                        ['Discutir estratégias de ataque na ala do rei com um parceiro', '10 min'],
                        ['Praticar a abertura que favorece o ataque na ala do rei', '20 min'],
                        ['Resolver problemas sobre como explorar fraquezas na ala do rei', '20 min'],
                        ['Analisar posições com forte ataque na ala do rei', '20 min'],
                        ['Jogar uma partida focando em abrir a ala do rei', '25 min'],
                        ['Simulações de finais onde o ataque na ala do rei foi decisivo', '10 min'],
                        ['Praticar jogadas em posições onde o ataque na ala do rei é forte', '20 min'],
                        ['Criar 5 jogadas para explorar a ala do rei', '25 min'],
                        ['Simulações de ataque na ala do rei em blitz', '20 min'],
                    ],
                    'attraction': [
                        ['Resolver 5 situações de atração em exercícios de tática', '20 min'],
                        ['Praticar 5 jogadas de atração em um jogo amistoso', '20 min'],
                        ['Criar 5 posições de atração em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos sobre atração', '20 min'],
                        ['Jogar uma partida buscando criar situações de atração', '25 min'],
                        ['Simulações de situações de atração em partidas', '20 min'],
                        ['Discutir estratégias de atração em posições complexas com um parceiro', '20 min'],
                        ['Resolver exercícios de atração em várias posições', '20 min'],
                        ['Simulações de atração em diferentes ritmos de jogo', '20 min'],
                        ['Praticar situações onde a atração é chave para a vitória', '20 min'],
                        ['Criar 5 jogadas para explorar a atração', '25 min'],
                        ['Simulações de atração em finais', '25 min'],
                        ['Resolver problemas sobre erros comuns na atração', '15 min'],
                        ['Analisar jogos que terminaram com jogadas de atração importantes', '20 min'],
                        ['Praticar a atração em aberturas e meio-jogo', '20 min'],
                    ],
                    'pinned': [
                        ['Resolver 5 exercícios de cravadas em situações variadas', '20 min'],
                        ['Praticar 5 jogadas de cravadas em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de cravadas em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de cravadas em posições comuns', '15 min'],
                        ['Jogar uma partida focando em utilizar cravadas para ganhar material', '25 min'],
                        ['Simulações de cravadas em jogos online', '20 min'],
                        ['Resolver problemas de cravadas em várias posições', '15 min'],
                        ['Praticar cravadas em finais em um aplicativo de xadrez', '20 min'],
                        ['Analisar posições onde cravadas levaram a vitórias decisivas', '20 min'],
                        ['Discutir a aplicação de cravadas em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de cravadas em finais', '20 min'],
                        ['Simulações de cravadas em diferentes ritmos de jogo', '20 min'],
                        ['Criar 5 jogadas para explorar cravadas em uma partida', '25 min'],
                        ['Praticar táticas de cravadas em blitz', '20 min'],
                        ['Resolver problemas sobre como evitar cravadas', '15 min'],
                    ],
                    'endgames': [
                        ['Resolver 5 problemas de finais simples (rei e peão)', '15 min'],
                        ['Praticar finais de torre e rei contra rei em um tabuleiro', '20 min'],
                        ['Resolver problemas práticos de finais de torre e peões', '20 min'],
                        ['Discutir finais com um parceiro de treino, focando em técnicas específicas', '20 min'],
                        ['Jogar uma partida focando em aplicar técnicas de finais', '25 min'],
                        ['Simulações de finais em jogos online, tentando vencer', '20 min'],
                        ['Análise de finais clássicos em jogos de mestres', '25 min'],
                        ['Praticar finais em situações diversas, buscando o resultado ideal', '25 min'],
                        ['Resolver 5 problemas de finais de peão (ex: dois peões contra rei)', '20 min'],
                        ['Praticar finais de rei e bispo contra rei', '20 min'],
                        ['Simulações de finais de peão e torre, focando em ganhar material', '20 min'],
                        ['Discutir estratégias de finais com um parceiro de treino', '20 min'],
                        ['Resolver exercícios sobre finais comuns e como vencê-los', '20 min'],
                        ['Praticar finais de peão contra rei em um aplicativo', '15 min'],
                        ['Analisar partidas que terminaram em finais simples', '20 min'],
                    ],
                    'fork': [
                        ['Resolver 10 problemas de garfo em situações práticas', '15 min'],
                        ['Praticar 5 jogadas de garfo em um jogo amistoso', '20 min'],
                        ['Criar 5 situações de garfo em um tabuleiro e discutir', '25 min'],
                        ['Resolver problemas práticos de garfos em várias posições', '15 min'],
                        ['Simulações de garfos em jogos online', '20 min'],
                        ['Análise de partidas que usaram garfos de forma eficaz', '20 min'],
                        ['Praticar garfos em finais em um aplicativo de xadrez', '20 min'],
                        ['Discutir a aplicação de garfos em posições específicas com um parceiro', '20 min'],
                        ['Resolver 5 problemas de garfos em várias situações', '20 min'],
                        ['Simulações de garfos em blitz, buscando material', '20 min'],
                        ['Criar 5 jogadas para explorar garfos em uma partida', '25 min'],
                        ['Praticar garfos em aberturas e meio-jogo', '20 min'],
                        ['Resolver problemas sobre como evitar ser garfado', '15 min'],
                        ['Simulações de garfos em diferentes ritmos de jogo', '20 min'],
                        ['Analisar jogadas de garfos em partidas anteriores', '20 min'],
                    ],
                    
                },
            };
            // Função para embaralhar um array
            function shuffleArray(array) {
                for (let i = array.length - 1; i > 0; i--) {
                    const j = Math.floor(Math.random() * (i + 1));
                    [array[i], array[j]] = [array[j], array[i]];
                }
                return array;
            }

            // Exemplo de como buscar atividades aleatórias respeitando o tempo
            selectedPuzzles.forEach(puzzle => {
                const puzzleActivities = activities[playerRating][puzzle] || [];
                let activitiesCount = 0;

                // Embaralha as atividades
                const shuffledActivities = shuffleArray(puzzleActivities);

                // Seleciona até duas atividades para cada ponto fraco
                shuffledActivities.forEach(activity => {
                    const timeInMinutes = parseInt(activity[1].split(' ')[0]);
                    if (timeAvailable >= timeInMinutes && activitiesCount < 2) {
                        const row = document.createElement('tr');
                        row.innerHTML = `<td>${activity[0]}</td><td>${activity[1]}</td>`;
                        table.appendChild(row);
                        timeAvailable -= timeInMinutes;
                        activitiesCount++;
                    }
                });
            });
            // Adiciona atividades gerais
            const generalActivities = {
                'iniciantes': [
                    ['Partida jogada (exemplo: 1.e4 e5)', '20 min'],
                    ['Assistir a vídeo do GM Evandro Barbosa sobre aberturas', '15 min'],
                    ['Exercícios de xeque-mate em 1', '10 min'],
                    ['Análise de uma partida própria', '15 min'],
                    ['Jogar contra computador (dificuldade baixa)', '20 min'],
                    ['Vídeo sobre táticas simples do Rafael Chess', '10 min'],
                    ['Jogo em duplas', '15 min'],
                    ['Assistir a vídeo de táticas do GM Krikor', '15 min'],
                    ['Prática de aberturas básicas', '20 min'],
                    ['Desenho do tabuleiro e compreensão de posições', '10 min'],
                ],
                '1000': [
                    ['Análise de partida (ex: Magnus Carlsen)', '15 min'],
                    ['Estudo de finais básicos', '20 min'],
                    ['Assistir a vídeo do GM Evandro sobre finais', '15 min'],
                    ['Exercícios de cálculo tático', '15 min'],
                    ['Jogar o max. partidas em formato “3 min”', '20 min'],
                    ['Assistir a vídeo do GM Krikor sobre estratégia', '15 min'],
                    ['Prática de conversão de vantagem material', '15 min'],
                    ['Vídeo sobre aberturas do Rafael Chess', '10 min'],
                    ['Simulações de finais simples', '20 min'],
                    ['Análise de erros em partidas próprias', '15 min'],
                ],
                '1200': [
                    ['Estudo de tática', '20 min'],
                    ['Análise de erros comuns', '15 min'],
                    ['Jogar partidas seguida de análise', '20 min'],
                    ['Assistir a vídeo do GM Krikor sobre meio-jogo', '15 min'],
                    ['Exercícios de cálculo de variantes', '15 min'],
                    ['Revisão de partidas de mestres', '20 min'],
                    ['Prática de diferentes finais', '20 min'],
                    ['Assistir a vídeo do GM Evandro sobre táticas', '15 min'],
                    ['Simulações de partidas com diferentes ritmos', '20 min'],
                    ['Treino de tempo para decisões rápidas', '10 min'],
                ],
                '1400': [
                    ['Análise de partidas de mestres', '20 min'],
                    ['Estudo de estratégias de meio-jogo', '20 min'],
                    ['Treino de posições críticas', '15 min'],
                    ['Assistir a vídeo do Rafael Chess sobre estratégias', '15 min'],
                    ['Exercícios de ataque e defesa', '20 min'],
                    ['Simulações de finais avançados', '20 min'],
                    ['Análise de partidas com outros jogadores', '15 min'],
                    ['Prática de técnicas de sacrifício', '15 min'],
                    ['Análise crítica de suas partidas', '20 min'],
                    ['Revisão de estruturas de peões', '20 min'],
                ],
                '1600': [
                    ['Análise de finais avançados', '10 min'],
                    ['Estudo de táticas complexas', '10 min'],
                    ['Estudo de estruturas de peões e suas consequências', '15 min'],
                    ['Prática em blitz (3 min por partida seguida de análise)', '20 min'],
                    ['Revisão de variantes de aberturas e suas armadilhas', '20 min'],
                    ['Estudo de finais e suas técnicas (Magnus)', '20 min'],
                    ['Discussão sobre partidas com colegas', '15 min'],
                    ['Simulações de diferentes abordagens em meio-jogo', '15 min'],
                    ['Treino de defesa em posições de desvantagem', '10 min'],
                    ['Italiana, análise seguida de prática', '20 min'],
                    ['Estudo de partidas em níveis de grande mestre (nakamura)', '30 min'],
                    ['Prática de cálculo em quebra cabeças (lichess)', '10 min'],
                    ['Defesa Siciliana, análise e prática', '20 min'],
                    ['Revisão de jogos (Magnus)', '10 min'],
                    ['Treino de táticas de ataque a diferentes tipos de defesa', '20 min'],
                    ['Jogue 3 partidas seguidas (3 min cada e análise pós)', '20 min'],
                    ['Coreção de erros (tente jogar melhor que a ultima vez)', '15 min'],
                ],
                '1800': [
                    ['Estudo de grandes mestres', '10 min'],
                    ['Prática intensiva', '10 min'],
                    ['Análise detalhada de partidas com erros críticos', '30 min'],
                    ['Estudo de variantes menos comuns em aberturas', '10 min'],
                    ['Treinamento de posições de meio-jogo complexas', '30 min'],
                    ['Revisão de grandes finais e suas transições', '30 min'],
                    ['Exercícios de técnicas de sacrifício em meio-jogo', '10 min'],
                    ['Estudo de estratégias de endgame avançadas', '30 min'],
                    ['Prática de partidas em diferentes estilos de jogo', '10 min'],
                    ['Análise de suas partidas em detalhe com feedback', '15 min'],
                    ['Estudo de conceitos de xadrez dinâmico', '30 min'],
                    ['Jogue 1 partida rápida (10min) seguida de análise de erros', '20 min'],
                    ['Treinamento de visão de jogo', '30 min'],
                    ['Análise de posições críticas em meio-jogo', '5 min'],
                    ['Estudo de posições jogadas recentemente', '10 min'],
                    ['Prática de partidas recentes', '15 min'],
                    ['Jogar em torneios online com análise posterior', '1h'],
                    ['Cáuculos (rápida com análise e cálculo durante a partida)', '10 min'],
                    ['Coreção de erros (tente jogar melhor que a ultima vez)', '15 min'],
                ],
            };

            const shuffledGeneralActivities = generalActivities[playerRating].sort(() => 0.5 - Math.random());
            const numberOfActivities = Math.floor(Math.random() * 3) + 2; // De 2 a 4 atividades
            let activitiesCount = 0;

            // Adiciona atividades gerais
            shuffledGeneralActivities.forEach(activity => {
                if (activitiesCount < numberOfActivities) {
                    const timeInMinutes = parseInt(activity[1].split(' ')[0]);
                    if (timeAvailable >= timeInMinutes) {
                        const row = document.createElement('tr');
                        row.innerHTML = `<td>${activity[0]}</td><td>${activity[1]}</td>`;
                        table.appendChild(row);
                        timeAvailable -= timeInMinutes;
                        activitiesCount++;
                    }
                }
            });

            // Adiciona a tabela ao plano de treino
            const dayHeader = document.createElement('h3');
            dayHeader.innerText = `Treinamento para ${day}`;
            trainingPlan.appendChild(dayHeader);
            trainingPlan.appendChild(table);
        });
    } else {
        trainingPlan.innerHTML = '<p>Por favor, selecione pelo menos um dia para treinar e preencha todas as informações.</p>';
    }
});

